### ISSUE TITLE
Regex check is overzaelous

### ISSUE THREAD

**Issue by MidasLamb** [openfga/api#8]
See https://github.com/openfga/api/commit/b7cfc0cacffd406d8bfa7be9fc69109b26ab1344#r77087138

**Comment by rhamzeh** [comment]
@MidasLamb this should have been resolved in https://github.com/openfga/api/pull/6, are you still facing this issue?

**Comment by MidasLamb** [comment]
I used the docker image with tag 0.1.3, and it seems like it was still in there at that time. I can't immediately tell if #6 should be present in that tag or not?

**Comment by rhamzeh** [comment]
`0.1.3` was re-released this morning, could you please make sure to update (`docker pull openfga/openfga`) and then try running that version?

**Comment by MidasLamb** [comment]
@rhamzeh , I've just checked with 0.1.4 (as I see that version has been created in the meantime) and that worked!
